name: Create GitHub release and run build on JitPack

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '*.md'

jobs:
  build:
    name: Create GitHub release and run build on JitPack
    runs-on: ubuntu-latest
    permissions:
       contents: write
    steps:
        - uses: actions/checkout@v4.1.0

        - name: Get artifact version
          run: echo "VERSION=$(cat gradle.properties | grep artifactVersion | cut -d "=" -f2)" >> $GITHUB_ENV
            
        - name: Create GitHub release
          uses: ncipollo/release-action@v1.13.0
          with:
            name: v${{ env.VERSION }}
            tag: ${{ env.VERSION }}
            generateReleaseNotes: true

        - name: Run build on JitPack
          run: curl https://jitpack.io/com/github/${{ github.repository }}/${{ env.VERSION }}
